uppgift:
  version: 1.0
  path: /regel/maskinell
  aktivitet: "Beräkna ersättning för"

specifikation:
  id: 494726b5-5122-4efc-8a5d-578dcd44df0f
  version: 1.0
  namn: "Beräkna ersättning för vård av husdjur"
  uppgiftbeskrivning: "Beräknar ersättningsbelopp baserat på löneunderlag och antal dagar"
  verksamhetslogik: C
  roll: ANSVARIG_HANDLAGGARE
  applikationsId: 3.5.2
  applikationsversion: vard_av_husdjur_1.0

regel:
  id: caf86a5f-9776-4fce-a854-8d365fa75067
  version: 1.0
  namn: "Beräkna ersättning för vård av husdjur"
  beskrivning: "Beräknar 10% av specificerad lön per dag med godkänt ersättningsunderlag"

lagrum:
  id: 6955bd9b-2019-4589-a460-7bcfd8a43eb5
  version: 1.0
  giltigFom: 2010-02-11
  forfattning: Husdjursbalken
  kapitel: 4
  paragraf: 7
  stycke: 2
  punkt: 3